### ISSUE TITLE
Implement Database publisher

### ISSUE THREAD

**Issue by davezych** [davezych/shience#10]
Implement publisher for databases. 

Things to consider:
- How to handle creation of database tables
- Database migration/upgrades when Shience is updated
- What databases to support? Sql Server, Mysql, oracle, postgre?

**Comment by MovGP0** [comment]
you can use EntityFramework CodeFirst to create the tables for you. The user should provide the database provider and connection strings. This way you are database agnostic.  

You just need an initializer: 

```
public class MyDbContext : DbContext 
{
    public IDbSet<Foo> Foos { get; set; }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        Database.SetInitializer(new MyDbContextInitializer());

        base.OnModelCreating(modelBuilder);
    }
}

public class MyDbContextInitializer : DropCreateDatabaseIfModelChanges<MyDbContext>
{
    protected override void Seed(MyDbContext dbContext)
    {
        // seed data

        base.Seed(dbContext);
    }
} 
```

source: [Entity Framework 4.1 Code First not creating tables](http://stackoverflow.com/questions/7250297/entity-framework-4-1-code-first-not-creating-tables)

**Comment by MovGP0** [comment]
Note: because this has external dependencies, it should be put into an external library.

**Comment by MovGP0** [comment]
another thing: we might not want to ship a database provider, because the user probably has its own method. usually, the user would just provide an adapter method to his logging facility (ie. NLog, Serilog, etc.). 

This way, the developer/administrator can configure where the output should go to by setting an appropriate logging appender.

**Comment by MovGP0** [comment]
Also, the publisher should not be a [Functor](https://en.wikipedia.org/wiki/Function_object), but a function. 

Instead of: 
```
Shience.Shience.SetPublisher(new MyPublisher());
```

The user should write something like: 
```
Shience.Shience.SetPublisher(result => Log.Warn(...));
Shience.Shience.SetPublisher(MyPublisher.Publish);
```

The interface `IPublisher` would become obsolete.

**Comment by davezych** [comment]
#16 might negate this entirely. Let the user provide a function and they deal with it as they please.

**Comment by davezych** [comment]
@MovGP0 should we remove `IPublisher` and `SetPublisher` and just use the `New<TResult>([NotNull]string name, [NotNull]Action<ExperimentResult<TResult>> publish)` overload? The more I think about it, the more I don't see a need for a global publisher. Passing in a lambda is easy, and for more complicated publishing passing a static method works great, such as:

    static void MyPublish(ExperimentResult<bool> result)
    {
        //whatever
    }

    var science = Shience.New<bool>("test", MyPublish);

This also avoids having to implement various publishers, since users can easily specify their own.

**Comment by MovGP0** [comment]
yes, I agree with that. The user should provide his own publisher logic. It would also solve some issues with thread safety and unit testing.

**Comment by davezych** [comment]
:+1: I'll close this and open a new issue to track removing `SetPublisher`.
