### ISSUE TITLE
.Where() should be chainable

### ISSUE THREAD

**Issue by MovGP0** [davezych/shience#19]
It should be possible to chain multiple `.Where()` clauses on a single `Science` object. To do so, the `Skip` property should be refactored to an `IList<Func<bool>>` rather than an `bool`: 

```csharp
internal IList<Func<bool>> Skip { get; } = new List<Func<bool>>();
```

```csharp
public static Science<TResult> Where<TResult>(this Science<TResult> science, Func<bool> predicate)
{
    science.Skip.Add(predicate);
    return science;
}
```

The predicate should not be executed immediately, but at the time the `Science` object gets executed. The `.Execute()` and `.ExecuteAsync()` methods should check all conditions and break using

```csharp
if(science.Skip.Any(reason => reason())) return;
```

**Comment by MovGP0** [comment]
see also #4

**Comment by davezych** [comment]
Agreed.
