### ISSUE TITLE
Experiment should get additional extension methods

### ISSUE THREAD

**Issue by MovGP0** [davezych/shience#21]
There should be extension methods to make use of the `ExperimentResult` object more fluent: 

```csharp
science
    .Execute()
    .OnSuccess((controlResult, candidateResult, context) => ...)
    .OnError((controlResult, candidateResult, context) => ...)
```

**Comment by davezych** [comment]
`Execute` returns `TResult`, not `ExperimentResult<TResult>`. The reason for this is that the experiment results are really only useful in publishing, and the application flow only needs the result of the control function. 

I'm not sure I see a need to have it return an experiment result.

**Comment by MovGP0** [comment]
Sorry. I mixed up the order. What I meant was essentially that instead of: 
```csharp
Shience.New<bool>("name", HandleSuccessOrError(...)).Execute().
```
we could do something like: 
```csharp
Shience.New<bool>("name").
    .OnSuccess((controlResult, candidateResult, context) => HandleSuccess(...))
    .OnError((controlResult, candidateResult, context) => HandleError(...))
    .Execute()
```

**Comment by MovGP0** [comment]
the additional methods are implemented, but they need testing and documentation.
