### ISSUE TITLE
Remove IPublisher and SetPublisher

### ISSUE THREAD

**Issue by davezych** [davezych/shience#23]
As mentioned in #10, `IPublisher` and the `SetPublisher` method aren't needed anymore. We will only support setting a publisher per-test, when calling `New`:

    var science = Shience.New<bool>("test-name", (e) = { /*Do something with ExperimentResults } */);

**Comment by MovGP0** [comment]
maybe we should put the file publisher into the `Shience.Tests` library, since the user is probably not needing it except for reference how to implement his own method.

**Comment by davezych** [comment]
Readded.

**Comment by MovGP0** [comment]
I've re-implemented it as a `.PublishTo(result => ...)` extension method that allows for chaining in an local test branch. This way the user can choose to have multiple publish targets: 
```csharp
var result = Shience.New<bool>("somename")
   .Test(..., ...)
   .PublishTo(Log.Publish)
   .PublishTo(Console.Publish)
   .PublishTo(_ => ran = true)
   .Execute()
```

**Comment by MovGP0** [comment]
The existing documentation got updated, but the new version still needs additional documentation and testing.
