### ISSUE TITLE
Refactor names

### ISSUE THREAD

**Issue by davezych** [davezych/shience#28]
The `Shience`/`Science`/`Shience namespace` naming is all confusing. I propose:

- `Shience` namespace stays
- `Shience` -> `Science`
- `Science` -> `Experiment`

It also makes more sense. When instantiating a new test, you are essentially creating an experiment, the type should reflect that.

**Comment by MovGP0** [comment]
i would also rename the library to be in lower case, while keeping the namespace uppercase. 

this way I do not have to change the dependency forward and backward when referencing the project.

**Comment by MovGP0** [comment]
I would put everything into the main `Shience` namespace, since there are only very few classes.

**Comment by MovGP0** [comment]
I agree with the renaming to align more with the GitHub Science library.

**Comment by davezych** [comment]
Merged in #31. Closing.
