### ISSUE TITLE
Implement runif functionality

### ISSUE THREAD

**Issue by davezych** [davezych/shience#4]
Implement a `runif` functionality, which will allow specifying a predicate that determines whether or not to actually run the experiment. Example usages:

- If user is part of development group, run
- If user's age is < 25, run
- If user is performing action at 11:59PM, run

**Comment by MovGP0** [comment]
An alternative would be a fluent `.Where()` extension method. In my opinion this would be nicer, because developers are already used to the name, so they would remember it better.

**Comment by davezych** [comment]
Once #8 is implemented I agree that this should also be implemented with a fluent interface.
