### ISSUE TITLE
Use dynamic for contexts

### ISSUE THREAD

**Issue by davezych** [davezych/shience#5]
Right now the `contexts` param of the test method is a `params object[]`. Should it use `dynamic`?

**Comment by MovGP0** [comment]
I would go for both and also provide an overload with `IEmunerable contexts`. 

Personally, I prefer serializing the context in form of an `dynamic` object using a high-performance JSON library like [Jil](https://github.com/kevin-montrose/Jil).

**Comment by MovGP0** [comment]
The advantage of using an dynamic object is that I can preserve the name of the parameters inside the object: 

```csharp
var userCanRead = science.Test(
    control: (() => return UserPermissions.CheckUser(currentUser); ), 
    candidate: (() => return User.Can(currentUser, Permission.Read); ),
    contexts: new {
        class: nameof(MyClass), 
        method: nameof(Display), 
        currentUser, 
        timestamp: DateTime.UtcNow 
    }
);
```

Logging should ideally also provide the name and position of the code under test using reflection out of the box (think `CallerMemberNameAttribute`).
