### ISSUE TITLE
Testing write operations

### ISSUE THREAD

**Issue by MovGP0** [davezych/shience#9]
We should think about when and how to properly test write operations. 

Ie. when there are two different databases (one production and one test) and the write goes to different databases, then the comparer needs to check if the result in both databases is identical. 

There could be extension methods that support this scenario by also providing (`async`) read operations: 

```csharp
science
    .TestWrite(
        control: () => OldClass.WriteToOldDatabase(importantInformation), // returns void
        candidate: () => NewClass.WriteToNewDatabase(importantInformation) // returns void
    ).Test(
        control: () => OldClass.ReadFromOldDatabase(importantInformation),
        candidate: () => NewClass.ReadFromNewDatabase(importantInformation)
    );
```

Async version: 
```csharp
await science
    .TestWriteAsync(
        control: () => OldClass.WriteToOldDatabaseAsync(importantInformation), // returns void
        candidate: () => NewClass.WriteToNewDatabaseAsync(importantInformation) // returns void
    ).TestAsync(
        control: () => OldClass.ReadFromOldDatabaseAsync(importantInformation),
        candidate: () => NewClass.ReadFromNewDatabaseAsync(importantInformation)
    );
```

**Comment by davezych** [comment]
Write operations are... scary. I'm not sure whether they should be supported or not. The consensus on Scientist was to not experiment on write operations, rather always write with an old operation and then experiment on reads.

**Comment by MovGP0** [comment]
Well, we better leave it then for now, until someone comes up with an better idea.
